package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "ecommerce")
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private Users users;
	private Set<Cartitems> cartitemses = new HashSet<Cartitems>(0);

	public Cart() {
	}

	public Cart(Users users) {
		this.users = users;
	}

	public Cart(Users users, Set<Cartitems> cartitemses) {
		this.users = users;
		this.cartitemses = cartitemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CartID", unique = true, nullable = false)
	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
	public Set<Cartitems> getCartitemses() {
		return this.cartitemses;
	}

	public void setCartitemses(Set<Cartitems> cartitemses) {
		this.cartitemses = cartitemses;
	}

}
