package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "options", catalog = "ecommerce")
public class Options implements java.io.Serializable {

	private Integer optionId;
	private Optiongroups optiongroups;
	private String optionName;
	private List<Productoptions> productoptionses = new ArrayList<Productoptions>(0);

	public Options() {
	}

	public Options(Optiongroups optiongroups, String optionName, List<Productoptions> productoptionses) {
		this.optiongroups = optiongroups;
		this.optionName = optionName;
		this.productoptionses = productoptionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OptionID", unique = true, nullable = false)
	public Integer getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OptionGroupID")
	public Optiongroups getOptiongroups() {
		return this.optiongroups;
	}

	public void setOptiongroups(Optiongroups optiongroups) {
		this.optiongroups = optiongroups;
	}

	@Column(name = "OptionName", length = 50)
	public String getOptionName() {
		return this.optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "options")
	public List<Productoptions> getProductoptionses() {
		return this.productoptionses;
	}

	public void setProductoptionses(List<Productoptions> productoptionses) {
		this.productoptionses = productoptionses;
	}

}
