package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Optiongroups generated by hbm2java
 */
@Entity
@Table(name = "optiongroups", catalog = "ecommerce")
public class Optiongroups implements java.io.Serializable {

	private Integer optionGroupId;
	private String optionGroupName;
	private List<Options> optionses = new ArrayList<Options>();

	public Optiongroups() {
	}

	public Optiongroups(String optionGroupName, List<Options> optionses) {
		this.optionGroupName = optionGroupName;
		this.optionses = optionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OptionGroupID", unique = true, nullable = false)
	public Integer getOptionGroupId() {
		return this.optionGroupId;
	}

	public void setOptionGroupId(Integer optionGroupId) {
		this.optionGroupId = optionGroupId;
	}

	@Column(name = "OptionGroupName", length = 50)
	public String getOptionGroupName() {
		return this.optionGroupName;
	}

	public void setOptionGroupName(String optionGroupName) {
		this.optionGroupName = optionGroupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optiongroups")
	public List<Options> getOptionses() {
		return this.optionses;
	}

	public void setOptionses(List<Options> optionses) {
		this.optionses = optionses;
	}

}
