package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderdetails", catalog = "ecommerce")
public class Orderdetails implements java.io.Serializable {

	private Integer detailId;
	private Orders orders;
	private Products products;
	private String detailName;
	private float detailPrice;
	private String detailSku;
	private int detailQuantity;

	public Orderdetails() {
	}

	public Orderdetails(Orders orders, Products products, String detailName, float detailPrice, String detailSku,
			int detailQuantity) {
		this.orders = orders;
		this.products = products;
		this.detailName = detailName;
		this.detailPrice = detailPrice;
		this.detailSku = detailSku;
		this.detailQuantity = detailQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DetailID", unique = true, nullable = false)
	public Integer getDetailId() {
		return this.detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DetailOrderID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DetailProductID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "DetailName", nullable = false, length = 250)
	public String getDetailName() {
		return this.detailName;
	}

	public void setDetailName(String detailName) {
		this.detailName = detailName;
	}

	@Column(name = "DetailPrice", nullable = false, precision = 12, scale = 0)
	public float getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(float detailPrice) {
		this.detailPrice = detailPrice;
	}

	@Column(name = "DetailSKU", nullable = false, length = 50)
	public String getDetailSku() {
		return this.detailSku;
	}

	public void setDetailSku(String detailSku) {
		this.detailSku = detailSku;
	}

	@Column(name = "DetailQuantity", nullable = false)
	public int getDetailQuantity() {
		return this.detailQuantity;
	}

	public void setDetailQuantity(int detailQuantity) {
		this.detailQuantity = detailQuantity;
	}

}
