package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "ecommerce")
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private Users users;
	private float orderAmount;
	private String orderShipName;
	private String orderShipAddress;
	private String orderShipAddress2;
	private String orderCity;
	private String orderState;
	private String orderZip;
	private String orderCountry;
	private String orderPhone;
	private String orderFax;
	private float orderShipping;
	private float orderTax;
	private String orderEmail;
	private Date orderDate;
	private boolean orderShipped;
	private String orderTrackingNumber;
	private List<Orderdetails> orderdetailses = new ArrayList<Orderdetails>();

	public Orders() {
	}

	public Orders(Users users, float orderAmount, String orderShipName, String orderShipAddress,
			String orderShipAddress2, String orderCity, String orderState, String orderZip, String orderCountry,
			String orderPhone, String orderFax, float orderShipping, float orderTax, String orderEmail, Date orderDate,
			boolean orderShipped) {
		this.users = users;
		this.orderAmount = orderAmount;
		this.orderShipName = orderShipName;
		this.orderShipAddress = orderShipAddress;
		this.orderShipAddress2 = orderShipAddress2;
		this.orderCity = orderCity;
		this.orderState = orderState;
		this.orderZip = orderZip;
		this.orderCountry = orderCountry;
		this.orderPhone = orderPhone;
		this.orderFax = orderFax;
		this.orderShipping = orderShipping;
		this.orderTax = orderTax;
		this.orderEmail = orderEmail;
		this.orderDate = orderDate;
		this.orderShipped = orderShipped;
	}

	public Orders(Users users, float orderAmount, String orderShipName, String orderShipAddress,
			String orderShipAddress2, String orderCity, String orderState, String orderZip, String orderCountry,
			String orderPhone, String orderFax, float orderShipping, float orderTax, String orderEmail, Date orderDate,
			boolean orderShipped, String orderTrackingNumber, List<Orderdetails> orderdetailses) {
		this.users = users;
		this.orderAmount = orderAmount;
		this.orderShipName = orderShipName;
		this.orderShipAddress = orderShipAddress;
		this.orderShipAddress2 = orderShipAddress2;
		this.orderCity = orderCity;
		this.orderState = orderState;
		this.orderZip = orderZip;
		this.orderCountry = orderCountry;
		this.orderPhone = orderPhone;
		this.orderFax = orderFax;
		this.orderShipping = orderShipping;
		this.orderTax = orderTax;
		this.orderEmail = orderEmail;
		this.orderDate = orderDate;
		this.orderShipped = orderShipped;
		this.orderTrackingNumber = orderTrackingNumber;
		this.orderdetailses = orderdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderUserID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "OrderAmount", nullable = false, precision = 12, scale = 0)
	public float getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(float orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "OrderShipName", nullable = false, length = 100)
	public String getOrderShipName() {
		return this.orderShipName;
	}

	public void setOrderShipName(String orderShipName) {
		this.orderShipName = orderShipName;
	}

	@Column(name = "OrderShipAddress", nullable = false, length = 100)
	public String getOrderShipAddress() {
		return this.orderShipAddress;
	}

	public void setOrderShipAddress(String orderShipAddress) {
		this.orderShipAddress = orderShipAddress;
	}

	@Column(name = "OrderShipAddress2", nullable = false, length = 100)
	public String getOrderShipAddress2() {
		return this.orderShipAddress2;
	}

	public void setOrderShipAddress2(String orderShipAddress2) {
		this.orderShipAddress2 = orderShipAddress2;
	}

	@Column(name = "OrderCity", nullable = false, length = 50)
	public String getOrderCity() {
		return this.orderCity;
	}

	public void setOrderCity(String orderCity) {
		this.orderCity = orderCity;
	}

	@Column(name = "OrderState", nullable = false, length = 50)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "OrderZip", nullable = false, length = 20)
	public String getOrderZip() {
		return this.orderZip;
	}

	public void setOrderZip(String orderZip) {
		this.orderZip = orderZip;
	}

	@Column(name = "OrderCountry", nullable = false, length = 50)
	public String getOrderCountry() {
		return this.orderCountry;
	}

	public void setOrderCountry(String orderCountry) {
		this.orderCountry = orderCountry;
	}

	@Column(name = "OrderPhone", nullable = false, length = 20)
	public String getOrderPhone() {
		return this.orderPhone;
	}

	public void setOrderPhone(String orderPhone) {
		this.orderPhone = orderPhone;
	}

	@Column(name = "OrderFax", nullable = false, length = 20)
	public String getOrderFax() {
		return this.orderFax;
	}

	public void setOrderFax(String orderFax) {
		this.orderFax = orderFax;
	}

	@Column(name = "OrderShipping", nullable = false, precision = 12, scale = 0)
	public float getOrderShipping() {
		return this.orderShipping;
	}

	public void setOrderShipping(float orderShipping) {
		this.orderShipping = orderShipping;
	}

	@Column(name = "OrderTax", nullable = false, precision = 12, scale = 0)
	public float getOrderTax() {
		return this.orderTax;
	}

	public void setOrderTax(float orderTax) {
		this.orderTax = orderTax;
	}

	@Column(name = "OrderEmail", nullable = false, length = 100)
	public String getOrderEmail() {
		return this.orderEmail;
	}

	public void setOrderEmail(String orderEmail) {
		this.orderEmail = orderEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OrderDate", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "OrderShipped", nullable = false)
	public boolean isOrderShipped() {
		return this.orderShipped;
	}

	public void setOrderShipped(boolean orderShipped) {
		this.orderShipped = orderShipped;
	}

	@Column(name = "OrderTrackingNumber", length = 80)
	public String getOrderTrackingNumber() {
		return this.orderTrackingNumber;
	}

	public void setOrderTrackingNumber(String orderTrackingNumber) {
		this.orderTrackingNumber = orderTrackingNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public List<Orderdetails> getOrderdetailses() {
		return this.orderdetailses;
	}

	public void setOrderdetailses(List<Orderdetails> orderdetailses) {
		this.orderdetailses = orderdetailses;
	}

}
