package com.ecommerce.model;
// Generated Jul 10, 2018 8:17:37 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productoptions generated by hbm2java
 */
@Entity
@Table(name = "productoptions", catalog = "ecommerce")
public class Productoptions implements java.io.Serializable {

	private Integer productOptionId;
	private Options options;
	private Products products;
	private Double optionPriceIncrement;
	private int optionGroupId;

	public Productoptions() {
	}

	public Productoptions(Options options, Products products, int optionGroupId) {
		this.options = options;
		this.products = products;
		this.optionGroupId = optionGroupId;
	}

	public Productoptions(Options options, Products products, Double optionPriceIncrement, int optionGroupId) {
		this.options = options;
		this.products = products;
		this.optionPriceIncrement = optionPriceIncrement;
		this.optionGroupId = optionGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductOptionID", unique = true, nullable = false)
	public Integer getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(Integer productOptionId) {
		this.productOptionId = productOptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OptionID", nullable = false)
	public Options getOptions() {
		return this.options;
	}

	public void setOptions(Options options) {
		this.options = options;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "OptionPriceIncrement", precision = 22, scale = 0)
	public Double getOptionPriceIncrement() {
		return this.optionPriceIncrement;
	}

	public void setOptionPriceIncrement(Double optionPriceIncrement) {
		this.optionPriceIncrement = optionPriceIncrement;
	}

	@Column(name = "OptionGroupID", nullable = false)
	public int getOptionGroupId() {
		return this.optionGroupId;
	}

	public void setOptionGroupId(int optionGroupId) {
		this.optionGroupId = optionGroupId;
	}

}
